#!/bin/bash
set -e

# Create output directories if they don't exist
mkdir -p public/photos/Works/optimized/Getty\ Museum
mkdir -p public/photos/Works/optimized/Stairs
mkdir -p public/photos/Works/optimized/Thailand
mkdir -p public/photos/Works/optimized/Not\ Categorized

# Getty Museum
magick "public/photos/Works/Getty Museum/Getty Museum_001.tif" -resize 400x -quality 80 "public/photos/Works/optimized/Getty Museum/getty-museum-1-card.webp"
magick "public/photos/Works/Getty Museum/Getty Museum_001.tif" -resize 1600x -quality 80 "public/photos/Works/optimized/Getty Museum/getty-museum-1-large.webp"
magick "public/photos/Works/Getty Museum/Getty Museum_002.tif" -resize 400x -quality 80 "public/photos/Works/optimized/Getty Museum/getty-museum-2-card.webp"
magick "public/photos/Works/Getty Museum/Getty Museum_002.tif" -resize 1600x -quality 80 "public/photos/Works/optimized/Getty Museum/getty-museum-2-large.webp"
magick "public/photos/Works/Getty Museum/Getty Museum_003.tif" -resize 400x -quality 80 "public/photos/Works/optimized/Getty Museum/getty-museum-3-card.webp"
magick "public/photos/Works/Getty Museum/Getty Museum_003.tif" -resize 1600x -quality 80 "public/photos/Works/optimized/Getty Museum/getty-museum-3-large.webp"
magick "public/photos/Works/Getty Museum/Getty Museum_004.tif" -resize 400x -quality 80 "public/photos/Works/optimized/Getty Museum/getty-museum-4-card.webp"
magick "public/photos/Works/Getty Museum/Getty Museum_004.tif" -resize 1600x -quality 80 "public/photos/Works/optimized/Getty Museum/getty-museum-4-large.webp"
magick "public/photos/Works/Getty Museum/Getty Museum_005.tif" -resize 400x -quality 80 "public/photos/Works/optimized/Getty Museum/getty-museum-5-card.webp"
magick "public/photos/Works/Getty Museum/Getty Museum_005.tif" -resize 1600x -quality 80 "public/photos/Works/optimized/Getty Museum/getty-museum-5-large.webp"
magick "public/photos/Works/Getty Museum/11bGetty # 1 i.bmp" -resize 400x -quality 80 "public/photos/Works/optimized/Getty Museum/getty-museum-6-card.webp"
magick "public/photos/Works/Getty Museum/11bGetty # 1 i.bmp" -resize 1600x -quality 80 "public/photos/Works/optimized/Getty Museum/getty-museum-6-large.webp"
magick "public/photos/Works/Getty Museum/12Getty # 3GG.bmp" -resize 400x -quality 80 "public/photos/Works/optimized/Getty Museum/getty-museum-7-card.webp"
magick "public/photos/Works/Getty Museum/12Getty # 3GG.bmp" -resize 1600x -quality 80 "public/photos/Works/optimized/Getty Museum/getty-museum-7-large.webp"
magick "public/photos/Works/Getty Museum/SJ011 STEP2 FLAT.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Getty Museum/sj011-step2-flat-card.webp"
magick "public/photos/Works/Getty Museum/SJ011 STEP2 FLAT.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Getty Museum/sj011-step2-flat-large.webp"
magick "public/photos/Works/Getty Museum/SJ012 Step2 FLAT.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Getty Museum/sj012-step2-flat-card.webp"
magick "public/photos/Works/Getty Museum/SJ012 Step2 FLAT.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Getty Museum/sj012-step2-flat-large.webp"

# Stairs
magick "public/photos/Works/Stairs/320 S. Boston-11.tif" -resize 400x -quality 80 "public/photos/Works/optimized/Stairs/320-s-boston-11-card.webp"
magick "public/photos/Works/Stairs/320 S. Boston-11.tif" -resize 1600x -quality 80 "public/photos/Works/optimized/Stairs/320-s-boston-11-large.webp"
magick "public/photos/Works/Stairs/320 S. Boston-2.tif" -resize 400x -quality 80 "public/photos/Works/optimized/Stairs/320-s-boston-2-card.webp"
magick "public/photos/Works/Stairs/320 S. Boston-2.tif" -resize 1600x -quality 80 "public/photos/Works/optimized/Stairs/320-s-boston-2-large.webp"
magick "public/photos/Works/Stairs/Carnegie Mellon step 2.jpg.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Stairs/carnegie-mellon-step-2-card.webp"
magick "public/photos/Works/Stairs/Carnegie Mellon step 2.jpg.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Stairs/carnegie-mellon-step-2-large.webp"
magick "public/photos/Works/Stairs/ode to escher (monastery).tif" -resize 400x -quality 80 "public/photos/Works/optimized/Stairs/ode-to-escher-monastery-card.webp"
magick "public/photos/Works/Stairs/ode to escher (monastery).tif" -resize 1600x -quality 80 "public/photos/Works/optimized/Stairs/ode-to-escher-monastery-large.webp"
magick "public/photos/Works/Stairs/Getty Museum_003.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Stairs/getty-museum-3-card.webp"
magick "public/photos/Works/Stairs/Getty Museum_003.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Stairs/getty-museum-3-large.webp"
magick "public/photos/Works/Stairs/jpegs-1.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Stairs/jpegs-1-card.webp"
magick "public/photos/Works/Stairs/jpegs-1.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Stairs/jpegs-1-large.webp"
magick "public/photos/Works/Stairs/Salt Lake City Staircase.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Stairs/salt-lake-city-staircase-card.webp"
magick "public/photos/Works/Stairs/Salt Lake City Staircase.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Stairs/salt-lake-city-staircase-large.webp"
magick "public/photos/Works/Stairs/SJ012 Step2 FLAT.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Stairs/sj012-step2-flat-2-card.webp"
magick "public/photos/Works/Stairs/SJ012 Step2 FLAT.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Stairs/sj012-step2-flat-2-large.webp"
magick "public/photos/Works/Stairs/scanned neg-1.tif.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Stairs/scanned-neg-1-card.webp"
magick "public/photos/Works/Stairs/scanned neg-1.tif.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Stairs/scanned-neg-1-large.webp"
magick "public/photos/Works/Stairs/Spiral Stairs.tif" -resize 400x -quality 80 "public/photos/Works/optimized/Stairs/spiral-stairs-card.webp"
magick "public/photos/Works/Stairs/Spiral Stairs.tif" -resize 1600x -quality 80 "public/photos/Works/optimized/Stairs/spiral-stairs-large.webp"

# Thailand
magick "public/photos/Works/Thailand/Bud with cave-2.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Thailand/bud-with-cave-2-card.webp"
magick "public/photos/Works/Thailand/Bud with cave-2.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Thailand/bud-with-cave-2-large.webp"
magick "public/photos/Works/Thailand/Bell Temple, Buddhist, Bangkok.JPG" -resize 400x -quality 80 "public/photos/Works/optimized/Thailand/bell-temple-buddhist-bangkok-card.webp"
magick "public/photos/Works/Thailand/Bell Temple, Buddhist, Bangkok.JPG" -resize 1600x -quality 80 "public/photos/Works/optimized/Thailand/bell-temple-buddhist-bangkok-large.webp"
magick "public/photos/Works/Thailand/Basket Man with Lace Cloth, Bali.JPG" -resize 400x -quality 80 "public/photos/Works/optimized/Thailand/basket-man-with-lace-cloth-bali-card.webp"
magick "public/photos/Works/Thailand/Basket Man with Lace Cloth, Bali.JPG" -resize 1600x -quality 80 "public/photos/Works/optimized/Thailand/basket-man-with-lace-cloth-bali-large.webp"
magick "public/photos/Works/Thailand/SJ010 Step2 FLAT.jpg.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Thailand/sj010-step2-flat-card.webp"
magick "public/photos/Works/Thailand/SJ010 Step2 FLAT.jpg.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Thailand/sj010-step2-flat-large.webp"
magick "public/photos/Works/Thailand/Smiling Buddha-2.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Thailand/smiling-buddha-2-card.webp"
magick "public/photos/Works/Thailand/Smiling Buddha-2.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Thailand/smiling-buddha-2-large.webp"
magick "public/photos/Works/Thailand/untitled-1310.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Thailand/untitled-1310-card.webp"
magick "public/photos/Works/Thailand/untitled-1310.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Thailand/untitled-1310-large.webp"
magick "public/photos/Works/Thailand/SJ013 Step2 FLAT.jpg.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Thailand/sj013-step2-flat-card.webp"
magick "public/photos/Works/Thailand/SJ013 Step2 FLAT.jpg.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Thailand/sj013-step2-flat-large.webp"
magick "public/photos/Works/Thailand/untitled-1308.JPG" -resize 400x -quality 80 "public/photos/Works/optimized/Thailand/untitled-1308-card.webp"
magick "public/photos/Works/Thailand/untitled-1308.JPG" -resize 1600x -quality 80 "public/photos/Works/optimized/Thailand/untitled-1308-large.webp"
magick "public/photos/Works/Thailand/untitled-1309.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Thailand/untitled-1309-card.webp"
magick "public/photos/Works/Thailand/untitled-1309.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Thailand/untitled-1309-large.webp"

# Not Categorized
magick "public/photos/Works/Not Categorized/dogwood #1.tif" -resize 400x -quality 80 "public/photos/Works/optimized/Not Categorized/dogwood-card.webp"
magick "public/photos/Works/Not Categorized/dogwood #1.tif" -resize 1600x -quality 80 "public/photos/Works/optimized/Not Categorized/dogwood-large.webp"
magick "public/photos/Works/Not Categorized/Harwood museum-1.tif" -resize 400x -quality 80 "public/photos/Works/optimized/Not Categorized/harwood-museum-1-card.webp"
magick "public/photos/Works/Not Categorized/Harwood museum-1.tif" -resize 1600x -quality 80 "public/photos/Works/optimized/Not Categorized/harwood-museum-1-large.webp"
magick "public/photos/Works/Not Categorized/ItraTuppeer.tif" -resize 400x -quality 80 "public/photos/Works/optimized/Not Categorized/itratuppeer-card.webp"
magick "public/photos/Works/Not Categorized/ItraTuppeer.tif" -resize 1600x -quality 80 "public/photos/Works/optimized/Not Categorized/itratuppeer-large.webp"
magick "public/photos/Works/Not Categorized/ex4_samjoyner_CallaLily#2.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Not Categorized/calla-lily-2-card.webp"
magick "public/photos/Works/Not Categorized/ex4_samjoyner_CallaLily#2.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Not Categorized/calla-lily-2-large.webp"
magick "public/photos/Works/Not Categorized/philbrook winter reflection jet cp.tif" -resize 400x -quality 80 "public/photos/Works/optimized/Not Categorized/philbrook-winter-reflection-jet-cp-card.webp"
magick "public/photos/Works/Not Categorized/philbrook winter reflection jet cp.tif" -resize 1600x -quality 80 "public/photos/Works/optimized/Not Categorized/philbrook-winter-reflection-jet-cp-large.webp"
magick "public/photos/Works/Not Categorized/Rochester Panel-STEP 2.tif" -resize 400x -quality 80 "public/photos/Works/optimized/Not Categorized/rochester-panel-step-2-card.webp"
magick "public/photos/Works/Not Categorized/Rochester Panel-STEP 2.tif" -resize 1600x -quality 80 "public/photos/Works/optimized/Not Categorized/rochester-panel-step-2-large.webp"
magick "public/photos/Works/Not Categorized/indian girl scanned in black and white 100.bmp" -resize 400x -quality 80 "public/photos/Works/optimized/Not Categorized/indian-girl-scanned-in-black-and-white-100-card.webp"
magick "public/photos/Works/Not Categorized/indian girl scanned in black and white 100.bmp" -resize 1600x -quality 80 "public/photos/Works/optimized/Not Categorized/indian-girl-scanned-in-black-and-white-100-large.webp"
magick "public/photos/Works/Not Categorized/untitled-8.tif" -resize 400x -quality 80 "public/photos/Works/optimized/Not Categorized/untitled-8-card.webp"
magick "public/photos/Works/Not Categorized/untitled-8.tif" -resize 1600x -quality 80 "public/photos/Works/optimized/Not Categorized/untitled-8-large.webp"
magick "public/photos/Works/Not Categorized/untitled-59-3.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Not Categorized/untitled-59-3-card.webp"
magick "public/photos/Works/Not Categorized/untitled-59-3.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Not Categorized/untitled-59-3-large.webp"
magick "public/photos/Works/Not Categorized/SJ013 Step2 FLAT.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Not Categorized/sj013-step2-flat-2-card.webp"
magick "public/photos/Works/Not Categorized/SJ013 Step2 FLAT.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Not Categorized/sj013-step2-flat-2-large.webp"
magick "public/photos/Works/Not Categorized/Texas Jam_008.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Not Categorized/texas-jam-008-card.webp"
magick "public/photos/Works/Not Categorized/Texas Jam_008.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Not Categorized/texas-jam-008-large.webp"
magick "public/photos/Works/Not Categorized/World Peace Begins in the Imagination.jpg" -resize 400x -quality 80 "public/photos/Works/optimized/Not Categorized/world-peace-begins-in-the-imagination-card.webp"
magick "public/photos/Works/Not Categorized/World Peace Begins in the Imagination.jpg" -resize 1600x -quality 80 "public/photos/Works/optimized/Not Categorized/world-peace-begins-in-the-imagination-large.webp" 